---
name: dockerfile-linter

run-name: Dockerfile Linter

on:
  pull_request:
    branches:
      - "main"
    paths:
      - ".devcontainer/Dockerfile.*"
      - ".devcontainer/Dockerfile"

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  skip-duplicate-actions:
    name: Skip Duplicate Actions
    runs-on: ubuntu-latest
    steps:
      - uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          cancel_others: true
          concurrent_skipping: never

  trivy_scan:
    name: Trivy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Trivy vulnerability scanner in IaC mode
        uses: aquasecurity/trivy-action@master
        with:
          format: "table"
          ignore-unfixed: true
          scan-type: "config"
          severity: "CRITICAL,HIGH"
          trivyignores: ".trivyignore"
